### ISSUE TITLE
Install script fails silently if shasum not present

### ISSUE THREAD

**Issue by markgalpin** [carbonetes/diggity#64]
So I went to install this on AWS Linux 2023, and the shasum command wasn't there, and the install.sh script just died after step 2.  I needed to 'dnf install perl-Digest-SHA'

I thought about a docs update, but that would add too many ifs or buts based on distributions, probably.   But I think I could add a check for the command in the install.sh

**Comment by markgalpin** [comment]
See #65

**Comment by sairen-carbonetes** [comment]
Hi, @markgalpin. Thanks for raising an issue. I'll check and review your PR #65

**Comment by sairen-carbonetes** [comment]
Hello, @markgalpin. Upon checking your PR #65, your condition could cause an issue on Windows. I have already written a fix for this issue, PR #66. Let us know if this issue occurs after the fixes.
